#include <stdio.h>
#include <stdlib.h>


char menuProdutos(void){
	char opcao;

    system("clear");
	printf("/////////////////////////////////////////////////////////////////////////////////\n");
	printf("///                                                                           ///\n");
	printf("///          ===================================================              ///\n");
	printf("///          = = = = = = = = = = = = = = = = = = = = = = = = = =         	  ///\n");
	printf("///          = = = =    Sistema de Controle de Estoque   = = = =        	  ///\n");
	printf("///          = = = = = = = = = = = = = = = = = = = = = = = = = =         	  ///\n");
	printf("///          ===================================================        	  ///\n");
	printf("///            Developed by @dleonidas200 @MarlemM - Jan, 2021         	 	  ///\n");
	printf("///                                                                      	  ///\n");
	printf("/////////////////////////////////////////////////////////////////////////////////\n");
	printf("///                                                                    	      ///\n");
	printf("///           = = = = = = = = = = = = = = = = = = = = = =                 	  ///\n");
	printf("///           = = = = = = =  CADASTRO DE PRODUTOS = = = =               	  ///\n");
	printf("///           = = = = = = = = = = = = = = = = = = = = = =              		  ///\n");
	printf("///                                                                     	  ///\n");
	printf("///           1. Cadastrar um novo produto                              	  ///\n");
	printf("///           2. Pesquisar os dados de um produto                       	  ///\n");
	printf("///           3. Atualizar produto                                      	  ///\n");
	printf("///           4. Excluir um produto do sistema                          	  ///\n");
	printf("///           0. Voltar ao menu anterior                                	  ///\n");
	printf("///                                                                     	  ///\n");
	printf("///           Escolha a opção desejada:                                 	  ///\n");
	printf("///                                                                      	  ///\n");
	printf("///                                                                     	  ///\n");
	printf("/////////////////////////////////////////////////////////////////////////////////\n");
	printf("Qual a sua opção:\n");
	scanf("%c", &opcao);
	getchar();
    printf("\t\t\t>>> Tecle <ENTER> para continuar...\n");
	getchar();
	    return opcao;

}

void telaCadastrarNovoProduto(void){

	char codBarras[14];
	char nomeItem[51];
	char dataValidade[11];	

	system("clear");
	printf("/////////////////////////////////////////////////////////////////////////////////\n");
	printf("///                                                                           ///\n");
	printf("///          ===================================================              ///\n");
	printf("///          = = = = = = = = = = = = = = = = = = = = = = = = = =           	  ///\n");
	printf("///          = = = =    Sistema de Controle de Estoque   = = = =           	  ///\n");
	printf("///          = = = = = = = = = = = = = = = = = = = = = = = = = =         	  ///\n");
	printf("///          ===================================================        	  ///\n");
    printf("///        _______________________________________________________            ///\n");
    printf("///                                                                   		  ///\n");
    printf("///            *Cadastrar Novo Produto:                              		  ///\n");
    printf("///                                                                    		  ///\n");
    printf("///            - Código de Barras:                                     		  ///\n");
   	scanf("%d[0-9]", codBarras);
    getchar();
	printf("///            - Nome:                                              	   	  ///\n");
    scanf("%s[A-ZÁÉÍÓÚÂÊÔÇÀÃÕ a-záéíóúâêôçàãõ]", nomeItem);
	getchar();
	printf("///            - Data de Validade:                                  		  ///\n");
    scanf("%d[0-9/]", dataValidade);
	getchar();
    printf("///        _______________________________________________________     		  ///\n");
    printf("///                                                                 		  ///\n");
    printf("///          Deseja adicionar um novo produto (S/n) ?                 		  ///\n");
    printf("///        _______________________________________________________     		  ///\n");
    printf("///                                                                 		  ///\n");
    printf("///         Produto cadastrado com sucesso !                           		  ///\n");
    printf("///        _______________________________________________________  		  ///\n");
    printf("///                                                                 		  ///\n");
    printf("///              Código de Barras: %s \n", codBarras);
    printf("///              Nome: %s \n", nomeItem);
    printf("///              Data de Validade: %s \n", dataValidade);
    printf("///        _______________________________________________________     		  ///\n");
    printf("///                                                                           ///\n");
    printf("///                >>> Tecle <ENTER> para continuar...                        ///\n");
	printf("///////////////////////////////////////////////////////////////////////////////\n\n");
    printf("\t\t>>> Tecle <ENTER> para continuar...\n");
    getchar();

}

void telaPesquisarDadosDeUmProduto(void){
    char codBarras[14];
    system("clear");
    printf("/////////////////////////////////////////////////////////////////////////////////\n");
	printf("///                                                                           ///\n");
	printf("///          ===================================================              ///\n");
	printf("///          = = = = = = = = = = = = = = = = = = = = = = = = = =         	  ///\n");
	printf("///          = = = =    Sistema de Controle de Estoque   = = = =        	  ///\n");
	printf("///          = = = = = = = = = = = = = = = = = = = = = = = = = =         	  ///\n");
	printf("///          ===================================================        	  ///\n");
    printf("///        _______________________________________________________      	  ///\n");
    printf("///                                                                 		  ///\n");
    printf("///            *Pesquisar Dados de Um Produto:                       		  ///\n");
    printf("///                                                                 		  ///\n");
    printf("///            - Codigo de Barras:                                  		  ///\n");
    scanf("%s", &codBarras);
	printf("///        _______________________________________________________      	  ///\n");
    printf("///                                                                 		  ///\n");
    printf("///            *Produto Encontrado!                                  		  ///\n");
    printf("///                                                                 		  ///\n");
    printf("///            - Codigo de Barras:                                  		  ///\n");
    printf("///            - Nome:                                              		  ///\n");
    printf("///            - Data de Validade:                                  		  ///\n");
    printf("///        _______________________________________________________  		  ///\n");
    printf("///                                                                 		  ///\n");  
    printf("///            Não foi possível encontrar produto cadastrado com o     		  ///\n");    
    printf("///            código de barras informado.                             	      ///\n");    
    printf("///        _______________________________________________________  		  ///\n");
    printf("///                                                                 		  ///\n");
    printf("///////////////////////////////////////////////////////////////////////////////\n\n");
    printf("\t\t>>> Tecle <ENTER> para continuar...\n");
    getchar();

}

void telaAtualizarProduto(void){ 
	char codBarras[14];
    char nomeItem[51];
    char dataValidade[11];
    char resposta[2];
    char respostaLetras[2];
    char decisao[2];
	system("clear");
	system("clear");
    printf("/////////////////////////////////////////////////////////////////////////////////\n");
	printf("///                                                                           ///\n");
	printf("///          ===================================================              ///\n");
	printf("///          = = = = = = = = = = = = = = = = = = = = = = = = = =         	  ///\n");
	printf("///          = = = =    Sistema de Controle de Estoque   = = = =        	  ///\n");
	printf("///          = = = = = = = = = = = = = = = = = = = = = = = = = =         	  ///\n");
	printf("///          ===================================================        	  ///\n");
    printf("///        _______________________________________________________      	  ///\n");
    printf("///                                                                 		  ///\n");
    printf("///            *Atualizar Produto:                       	            	  ///\n");
    printf("///                                                                           ///\n");
    printf("///            - Código de Barras:                                            ///\n");
    scanf("%[0-9]", codBarras);
    getchar();
    printf("///        _______________________________________________________      	  ///\n");
    printf("///                                                                           ///\n");
    printf("///                       VALOR DE ENTRADA:                                   ///\n");
    printf("///                                                                           ///\n");
    printf("///            - Código de Barras: %s \n",codBarras);
    printf("///        _______________________________________________________      	  ///\n");
    printf("///                                                                           ///\n");
    printf("///            PRODUTO LOCALIZADO!                                            ///\n"); 
    printf("///                                                                           ///\n");
    printf("///            - Código de Barras:                                            ///\n");
    printf("///            - Nome do item:                                                ///\n");
    printf("///            - Data de Validade:                                            ///\n");
    printf("///        _______________________________________________________      	  ///\n");
    printf("///                                                                           ///\n");  
    printf("///            Não foi possível encontrar produto cadastrado com             ///\n");
    printf("///            o código de barras informado.                                  ///\n");    
    printf("///        _______________________________________________________      	  ///\n");
    printf("///                                                                           ///\n");
    printf("///            - Deseja alterar todos os valores (S/N)? ");
    scanf("%[SNsn]", resposta);
    getchar();
    printf("///        _______________________________________________________      	  ///\n");
    printf("///                                                                           ///\n");
    printf("///                       VALOR DE ENTRADA:                                   ///\n");
    printf("///                                                                           ///\n");
    printf("///            - Opção escolhida: %s \n",resposta);
    printf("///        _______________________________________________________      	  ///\n");
    printf("///                                                                           ///\n");
    printf("///           INFORME OS NOVOS VALORES DO PRODUTO:                            ///\n");
    printf("///                                                                           ///\n");
    printf("///            - Novo Nome: ");
    scanf("%[A-ZÁÉÍÓÚÂÊÔÇÀÃÕ a-záéíóúâêôçàãõ]", nomeItem);
    getchar();
    printf("///            - Nova Data Val. (dd/mm/aaaa): ");
    scanf("%[0-9/]", dataValidade);
    getchar();
    printf("///        _______________________________________________________      	  ///\n");
    printf("///                                                                           ///\n");
    printf("///                       VALORES DE ENTRADA:                                 ///\n");
    printf("///                                                                           ///\n");
    printf("///                          Nome: %s \n", nomeItem);
    printf("///              Data de Validade: %s \n", dataValidade);
    printf("///        _______________________________________________________      	  ///\n");
    printf("///                                                                           ///\n");
    printf("///           ESCOLHA O CAMPO À ALTERAR:                                      ///\n");
    printf("///                                                                           ///\n");
    printf("///            - Digite 'a' para alterar o nome                               ///\n");
    printf("///            - Digite 'b' para alterar a validade                           ///\n");
    printf("///        _______________________________________________________      	  ///\n");
    printf("///                                                                           ///\n");
    printf("///            - Informe a sua opção: "); 
    scanf("%[A-E a-e]", respostaLetras);
    getchar();
    printf("///        _______________________________________________________      	  ///\n");
    printf("///                                                                           ///\n");
    printf("///                       VALOR DE ENTRADA:                                   ///\n");
    printf("///                                                                           ///\n");
    printf("///            - Opção escolhida: %s \n",respostaLetras);
    printf("///        _______________________________________________________      	  ///\n");
    printf("///                                                                           ///\n");
    printf("///(            - a) Novo Nome: ");
    scanf("%[A-ZÁÉÍÓÚÂÊÔÇÀÃÕ a-záéíóúâêôçàãõ]", nomeItem);
    getchar();
    printf("///(            - b) Nova Data de Validade (dd/mm/aaaa): ");
    scanf("%[0-9/]", dataValidade);
    getchar();
    printf("///        _______________________________________________________      	  ///\n");
    printf("///                                                                           ///\n");
    printf("///                       VALORES DE ENTRADA:                                 ///\n");
    printf("///                                                                           ///\n");
    printf("///                          Nome: %s \n", nomeItem);
    printf("///              Data de Validade: %s \n", dataValidade);
    printf("///        _______________________________________________________      	  ///\n");
    printf("///                                                                           ///\n");
    printf("///            - Confirmar operação (S/N) ? ");
    scanf("%[SNsn]", decisao);
    getchar();
    printf("///        _______________________________________________________      	  ///\n");
    printf("///                                                                           ///\n");
    printf("///                       VALOR DE ENTRADA:                                   ///\n");
    printf("///                                                                           ///\n");
    printf("///            - Opção escolhida: %s \n",decisao);
    printf("///        _______________________________________________________      	  ///\n");
    printf("///                                                                           ///\n");
    printf("///            Produto alterado com sucesso!                                  ///\n");
    printf("///        _______________________________________________________      	  ///\n");
    printf("///                                                                           ///\n");
    printf("///            Operação cancelada!                                            ///\n"); 
    printf("///        _______________________________________________________      	  ///\n");
    printf("///                                                                           ///\n");
    printf("///////////////////////////////////////////////////////////////////////////////\n\n");
    printf("\t\t>>> Tecle <ENTER> para continuar...\n");
    getchar();
}


void telaExcluirUmProdutoDoSistema(void) {
	char codBarras[14];
	char resposta[2];

	system("clear");
    printf("/////////////////////////////////////////////////////////////////////////////////\n");
	printf("///                                                                           ///\n");
	printf("///          ===================================================              ///\n");
	printf("///          = = = = = = = = = = = = = = = = = = = = = = = = = =         	  ///\n");
	printf("///          = = = =    Sistema de Controle de Estoque   = = = =        	  ///\n");
	printf("///          = = = = = = = = = = = = = = = = = = = = = = = = = =         	  ///\n");
	printf("///          ===================================================        	  ///\n");
    printf("///        _______________________________________________________      	  ///\n");
    printf("///                                                                 		  ///\n");
    printf("///            *Excluir Um Produto do Sistema:                       		  ///\n");
	printf("///                                                                           ///\n");
    printf("///            - Código de Barras:                                 		      ///\n");
    scanf("%[0-9]", codBarras);
    printf("///        _______________________________________________________      	  ///\n");
    printf("///                                                                 		  ///\n");
    printf("///            PRODUTO LOCALIZADO!                                  		  ///\n");
    printf("///                                                                 		  ///\n");
    printf("///            - Codigo de Barras:                                  		  ///\n");
    printf("///            - Nome:                                              		  ///\n");
    printf("///            - Data de Validade:                                  		  ///\n");
	printf("///        _______________________________________________________      	  ///\n");
    printf("///                                                                 		  ///\n");  
    printf("///            Não foi possível encontrar produto cadastrado com o     		  ///\n");    
    printf("///            código de barras informado.                           		  ///\n");    
    printf("///        _______________________________________________________      	  ///\n");
    printf("///                                                                 		  ///\n");
    printf("///            - Confirmar operação (S/n): S                        		  ///\n");
    scanf("%[SNsn]", resposta);
	printf("///                                                                 		  ///\n");
    printf("///            Produto excluído com sucesso!                        		  ///\n");
    printf("///        _______________________________________________________      	  ///\n");
    printf("///                                                                 		  ///\n");
    printf("///            - Confirmar operação (S/n): N                        		  ///\n");
    scanf("%[SNsn]", resposta);
	printf("///                                                                 		  ///\n");
    printf("///            Operação cancelada!                                  		  ///\n");
    printf("///        _______________________________________________________      	  ///\n");
    printf("///                                                                 		  ///\n");
    printf("///////////////////////////////////////////////////////////////////////////////\n\n");
    printf("\t\t>>> Tecle <ENTER> para continuar...\n");
    getchar();
}